### ISSUE TITLE
nudity/profanity overlay are missing.

### ISSUE THREAD

**Issue by ericvlog** [jwishon/plex-meta.manger#1]
I follow and configure for this, but the nudity/profanity overlays is missing do u know how make this works? thanks.

![Untitled](https://github.com/user-attachments/assets/6f6d3ff9-fe10-488f-adf3-79b513588b24)

**Comment by jwishon** [comment]
The overlay files are in the correct directory and they show on mine
![SNAG-0249](https://github.com/user-attachments/assets/4e6eba83-2484-4f48-b7df-349ce1dc0500)

**Comment by ericvlog** [comment]
> The overlay files are in the correct directory and they show on mine ![SNAG-0249](https://private-user-images.githubusercontent.com/26937337/380739688-4e6eba83-2484-4f48-b7df-349ce1dc0500.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjcyNDUsIm5iZiI6MTczMDEyNjk0NSwicGF0aCI6Ii8yNjkzNzMzNy8zODA3Mzk2ODgtNGU2ZWJhODMtMjQ4NC00ZjQ4LWI3ZGYtMzQ5Y2UxZGMwNTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDE0NDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMGMzM2E4ZDcwMDkzZDJhMzYzMDIwYjE4OTkxNjE3YjMzMDM1NjcwZjMxNjc4MzU3OGQwNDUzZTJhODhiNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7TJuNyowOggFMlsedxV6-5j5qK0ECEqiPl928J0jzic)

I open helped thread on discord the moderator reply he also cannot get `mass_imdb_parental_labels` to working either.

https://discord.com/channels/822460010649878528/1300458266987466875

Thanks.

**Comment by jwishon** [comment]
Fixed with new Kometa release
